site_name: PONの勉強部屋
site_url: https://ykitaza.github.io/my-study/
docs_dir: src
use_directory_urls: false

exclude_docs: |
  技術調査/index.md
  **/@resources/*
  directory_to_exclude/*

theme:
  features:
    - navigation.top
    - navigation.tabs
    - navigation.tracking 
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link    
    - grid                 
    - toc.integrate      # 右側のナビゲーションを本文に統合
    - navigation.expand  # 左側のナビゲーションをデフォルトで折りたたむ
  name: material
  language: ja
  palette:
    - scheme: default
      primary: indigo  
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Noto Sans JP
    code: Inconsolata
repo_url: https://github.com/ykitaza/my-study.git
repo_name: my-study
plugins:
  - search
  - markmap:
      base_path: src
      encoding: utf-8
      file_extension: .mm.md
      template_name: markmap.template
  - include-markdown:
      opening_tag: "{%"
      closing_tag: "%}"
extra_css:
  - style.css
  - "https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
markdown_extensions:
  - footnotes
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - def_list
  - tables
  - admonition
  - codehilite:
      noclasses: true
      pygments_style: colorful
      linenums: true
  - pymdownx.keys
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.blocks.caption
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs
  - https://unpkg.com/d3@7/dist/d3.min.js
  - https://unpkg.com/markmap-lib@0.15.3/dist/browser/index.js
  - https://unpkg.com/markmap-view@0.15.3/dist/browser/index.js